CREATE TABLE Person (
    id SERIAL PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    balance INTEGER NOT NULL CHECK (balance >= 0),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Transfer (
    id SERIAL PRIMARY KEY,
    sen_id INTEGER REFERENCES Person(id),
    rec_id INTEGER REFERENCES Person(id),
    amount INTEGER NOT NULL CHECK (amount >= 0),
    completed TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);